### ISSUE TITLE
availability question: old version with config files (instead of command line)?

### ISSUE THREAD

**Issue by arshbucks** [fractal-code/meteor-azure#41] opened 2017-08-06 01:39 UTC
Was wondering if you still happen to have the old version (with the bash deployment script + config file).

I like the ability to automatically deploy from source control directly, vs manually from command line.

If the command line is the only version available, we should delete the config file + deployment folder right?

Thank you!

**Comment by ramijarrar** [comment] 2017-08-06 02:01
We no longer support 1.x, but you can download/view any version from the [release history](https://github.com/fractal-code/meteor-azure/releases) (though we do not recommend this).

If you want to hook up v2 deployments with source control, just configure an external CI tool (e.g CircleCI which is free) to run the command for you.

**Comment by arshbucks** [comment] 2017-08-06 04:08
Gotcha, thanks. Trying to use the cmd line version, but getting the error below. Am I doing it wrong?

meteor-azure --settings ../privateDeploymentFiles/settingsDev.json --web-config ../privateDeploymentFiles/httpsMulticoreWeb.config --debug

I have tried wrapping the paths in " ", and the settings file hasthe exact same structure as your example (except there is an extra "MAIL_URL" in the envVariables.)

**Comment by ramijarrar** [comment] 2017-08-06 04:14
What is the error?

**Comment by arshbucks** [comment] 2017-08-06 04:27
Whoops - forgot to paste that in:
error:   Could not read settings file at '../privateDeploymentFiles/settingsDev.json'

**Comment by ramijarrar** [comment] 2017-08-06 06:53
The path is based on the directory the command runs in, can you double-check it's pointing to the right file? (try running ``cat  "../privateDeploymentFiles/settingsDev.json"`` to confirm)

**Comment by arshbucks** [comment] 2017-08-06 07:05
On windows I did:
type "..\privateDeploymentFiles\settingsDev.json"
and it will output the file content to the console.

However, I also tried running meteor-azure with the path containing: backslashes, backslashes+quotations, and Fully-Qualified paths (with forward/back slashes and/or quotations) - same error for all.

Could you confirm this error only shows up when it cannot find the file, and not when it has trouble reading the file content?

**Comment by ramijarrar** [comment] 2017-08-06 07:12
Can you try running meteor with the same settings file (that will confirm the file content is valid)?

**Comment by arshbucks** [comment] 2017-08-06 07:27
good call - found an extra comma.

(copied the example settings here http://meteor-azure.readthedocs.io/en/latest/getting-started.html - there's a trailing comma after envVariables. Sometimes that doesn't present a problem..maybe it does in the settings JSON. My fault though for not thinking of that first).

**Comment by ramijarrar** [comment] 2017-08-06 07:28
Good catch, I'll fix this in the documentation.

Let me know if you have any further issues.

**Comment by arshbucks** [comment] 2017-08-06 07:31
Thanks - appreciate the hard work & prompt responses!

**Comment by arshbucks** [comment] 2017-08-06 07:58
My deployment did finish properly according to the CLI - but I only see "The page cannot be displayed because an internal server error has occurred." on the site.

I tried accessing kudu logs via curl -u {username} https://{sitename}.scm.azurewebsites.net/api/logstream
(and using the same FTP credentials used to deploy), but get exactly nothing after connecting...

Any ideas? (Lmk if you prefer to move to a separate issue...)

**Comment by ramijarrar** [comment] 2017-08-06 08:00
Can you try refreshing after a few minutes? Still the same result?

**Comment by arshbucks** [comment] 2017-08-06 08:02
Yup - same result. The logstream sent "No new traces" each of the past 5 minutes

**Comment by ramijarrar** [comment] 2017-08-06 08:03
Can you open your site in the Azure portal and in "Diagnostics Logs" make sure "Application Logging (Filesystem)" is set to "On" and "Level" is set to "Information".

Once you've done that, restart the App and open the debug console (https://{your-site-name}.scm.azurewebsites.net/DebugConsole) then navigate to "LogFiles" > "Application" and check the contents of the latest \*-stdout-\*.txt

**Comment by arshbucks** [comment] 2017-08-06 08:16
the LogFiles/application folder seems to be empty -- Don't see a -stdout-.txt.

And looking at Web Server logs, all the GET requests seem to show 200 status.

Quick check: In application settings - it says METEOR_AZURE_NODE_VERSION set to "v4.8.4". That ok? should there be a "v"?

**Comment by ramijarrar** [comment] 2017-08-06 08:18
Yeah that's fine, Node/NPM format versions differently. Is "Application Logging (Filesystem)" enabled on the Azure portal?

**Comment by arshbucks** [comment] 2017-08-06 08:21
Yeah, I set it to Information & restarted the app. Let me try it again - seems like it might have gotten re set to "error" somehow in the interim - just looked at it again

**Comment by arshbucks** [comment] 2017-08-06 08:24
Nope - still nothing.  No stdout file...

**Comment by ramijarrar** [comment] 2017-08-07 01:59
Closing as per external discussion,

(For reference: issue was caused by a misconfigured web config)

**Closed as completed by ramijarrar** 2017-08-07 01:59 UTC
