### ISSUE TITLE
Request body larger than maxBodyLength limit

### ISSUE THREAD

**Issue by XAMelleOH** [fractal-code/meteor-azure#52] opened 2018-03-05 09:20 UTC
If you are reporting a bug, please be sure to include the following:

- Operating system: MacOS 10.13.3
- Meteor version: 1.6.1
- Package version: meteor-azure@2.0.8
- Command output with debug mode enabled
```
info:    Authenticating with service principal
debug:   completed Azure authentication
info:    Updating Azure application settings
debug:   set environment variables
debug:   set Meteor settings
debug:   set Kudu deployment settings
debug:   set Node to v8.9.4
debug:   set NPM to v5.6.0
info:    Compiling application bundle
debug:   generate meteor build
debug:   add custom web config
debug:   checking for broken symlinks
debug:   create tarball
info:    Deploying bundle tarball
error:   Request body larger than maxBodyLength limit
```

**Comment by ramijarrar** [comment] 2018-03-05 09:30
This issue was [fixed](https://github.com/fractal-code/meteor-azure/commit/4de0fade0c80764b2061e2f58ecbb1124d8ba1d5) in v2.1.0-rc.1 (which is fully stable and only pending documentation of some new features to go live). Please upgrade and let me know if you have any further problems. Closing for now.

**Comment by XAMelleOH** [comment] 2018-03-05 10:04
Still exists:

```
debug:   check Meteor is installed
debug:   check for incompatible 'force-ssl' package
debug:   check current Meteor release >= 1.4
info:    Validating settings file
debug:   check valid json exists
debug:   check data follows schema
debug:   *****: configure kudu api
info:    Validating Kudu connection
info:    *****: Authenticating with service principal
debug:   *****: completed Azure authentication
info:    *****: Updating Azure application settings
debug:   *****: retrieve existing values
debug:   *****: set environment variables
debug:   *****: set Meteor settings
debug:   *****: set Kudu deployment settings
debug:   *****: set Node to v8.9.4
debug:   *****: set NPM to v5.6.0
debug:   *****: serialise values
debug:   *****: push new settings
info:    Compiling application bundle
debug:   generate meteor build
debug:   add custom web config
debug:   checking for broken symlinks
debug:   create tarball
info:    *****: Deploying bundle tarball
error:   *****: Request body larger than maxBodyLength limit
```

**Comment by ramijarrar** [comment] 2018-03-05 10:07
You'll need to rebuild your node_modules directory (the cause of the issue was in a bad package upstream). Can you try running the following first and then deploy again:

```bash
rm -rf node_modules
meteor npm install
```

**Comment by XAMelleOH** [comment] 2018-03-05 10:11
Already tried that => still not working.

Also, updated npm and relaunched Terminal => no luck

**Comment by ramijarrar** [comment] 2018-03-05 10:24
Can you post the contents of your package lock / shrinkwrap? (I'm mainly interested in the versions for the package "follow-redirects")

**Comment by XAMelleOH** [comment] 2018-03-05 10:28
> ```
>     "axios": {
>       "version": "0.17.1",
>       "resolved": "https://registry.npmjs.org/axios/-/axios-0.17.1.tgz",
>       "integrity": "sha1-LY4+XQvb1zJ/kbyBT1xXZg+Bgk0=",
>       "dev": true,
>       "requires": {
>         "follow-redirects": "1.4.1",
>         "is-buffer": "1.1.6"
>       }
>     },
> ```

**Comment by ramijarrar** [comment] 2018-03-05 10:56
Thanks for this - I can see what's going on now and it's clear the temporary fix wasn't sufficient to eliminate the problem for all apps. Fortunately the necessary patch has since been [merged](https://github.com/axios/axios/pull/1287/files) upstream so I'm finally able to implement a proper solution (by actually configuring the problematic 'maxBodyLength' property).

I'll try and push this out in the new few hours. If you need to deploy something urgently in the meantime just use the tool [globally](http://meteor-azure.readthedocs.io/en/latest/installation.html#global-usage).

**Comment by ramijarrar** [comment] 2018-03-05 13:15
v2.1.0-rc.2 has now been released which should resolve this. Can you please test again and let me if you have any further issues?

**Comment by ramijarrar** [comment] 2018-03-05 13:46
I've just released a new version (2.1.0-rc.3) which should resolve this. Can you please test again and let me if you have any further issues?

**Comment by ramijarrar** [comment] 2018-03-05 23:37
Closing this for now. Please re-open if you have any further issues.

**Closed as completed by ramijarrar** 2018-03-05 23:37 UTC
Labels: bug

**Comment by XAMelleOH** [comment] 2018-03-06 04:54
I confirm, latest release solved the issue. Thank you very much for fast fix!
